Zone counter trigger strategies
DeGirum/degirum_tools pull request #44
Opened 2024-07-11 19:14 UTC by nklimov23

2024-07-11 22:07 UTC, vlad-nn requested changes

2024-07-11 22:07 UTC, vlad-nn commented on degirum_tools/object_tracker.py
> +    object in the `result.results[]` list, keeps its frame-to-frame track, assigning that track a
Please update the comment below to reflect your change in the semantic of `trails` dictionary values: before it contained anchor points, now it contains bboxes.

2024-07-11 22:07 UTC, vlad-nn commented on degirum_tools/object_tracker.py
> -                tracked_objects[:, 2:], self._anchor_point
Now anchor_point parameter is not used anywhere in this file, so lets just remove it from API altogether.

2024-07-11 22:07 UTC, vlad-nn commented on degirum_tools/math_support.py
> +def xyxy2xyxyxyxy(x: np.ndarray) -> np.ndarray:
Not very nice looking function name. May be get_all_rect_corners?
Or calc_all_rect_corners? Or tlbr2allcorners?

2024-07-11 22:07 UTC, vlad-nn commented on degirum_tools/zone_count.py
> +        timeout_frames: number of frames to buffer when an object disappears from zone
It is not clear from this comment, what all three parameters actually used for. Please rephrase.

At least you need to mention that IoPA method of detection is used only when `triggering_positions` is None. And in `triggering_positions` comment please mention that it is optional.

Also elaborate more on `bounding_box_scale`: why it is needed and how to use it.

2024-07-11 22:07 UTC, vlad-nn commented on degirum_tools/zone_count.py
> +        triggering_positions: list[AnchorPoint],
Annotate `triggering_positions` as Optional[...]

Also make sure all your new annotations are Python 3.8 compatible. 
list[...] is not. You need you use List[...]

2024-07-11 23:11 UTC, nklimov23 commented on degirum_tools/object_tracker.py
> -                tracked_objects[:, 2:], self._anchor_point
It is still present in the annotate() method for visualization purposes.

2024-07-11 23:13 UTC, nklimov23 commented on degirum_tools/math_support.py
> +def xyxy2xyxyxyxy(x: np.ndarray) -> np.ndarray:
Yeah it could be better. I chose tlbr2allcorners.

2024-07-11 23:37 UTC, vlad-nn commented on degirum_tools/object_tracker.py
> -                tracked_objects[:, 2:], self._anchor_point
> It is still present in the annotate() method for visualization purposes.

At least, lets remove it from _Tracer class - it is not used there.
And place a clear comment in ObjectTracker constructor, that this parameters is used only for showing annotations.

2024-07-12 01:18 UTC, vlad-nn requested changes
Since that zone counting becomes rather complex functionality, it makes sense to write some unit tests for it. At least to test few sweet paths.

2024-07-12 01:18 UTC, vlad-nn commented on degirum_tools/zone_count.py
> +        iopa_threshold: Optional[float] = 0.0,
Please be advised that `Optional` annotation means that this parameter is allowed to be `None`. If it is **not** allowed to be `None`, then remove `Optional`.
Here this parameter is not optional, but has default value. It is different thing.

2024-07-14 23:51 UTC, vlad-nn approved these changes

2024-07-15 17:40 UTC, merged